### ISSUE TITLE
Unable to run list_instance script

### ISSUE THREAD

**Issue by kk21986** [AnykeyNL/OCI-Python#2]
When I tried to run the list_instances script getting the below error,

```:~/.oci$ python3.6 list_instances.py
Traceback (most recent call last):
  File "list_instances.py", line 19, in <module>
    import shapes
  File "/usr/local/lib/python3.6/dist-packages/shapes/__init__.py", line 1, in <module>
    from Shape import Shape
ModuleNotFoundError: No module named 'Shape'
```

Here are the packages I have installed it 

```$ pip3.6 freeze
argh==0.26.2
arrow==0.10.0
asn1crypto==0.24.0
attrs==17.4.0
Automat==0.6.0
beautifulsoup4==4.7.1
blinker==1.4
bs4==0.0.1
certifi==2018.1.18
cffi==1.12.3
chardet==3.0.4
click==6.7
cloud-init==19.1
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
cryptography==2.4.2
cycler==0.10.0
diagram==0.2.27
distro-info===0.18ubuntu0.18.04.1
httplib2==0.9.2
httpsig-cffi==15.0.0
hyperlink==17.3.1
idna==2.6
incremental==16.10.1
Jinja2==2.10
jmespath==0.9.3
jsonpatch==1.16
jsonpointer==1.10
jsonschema==2.6.0
kiwisolver==1.1.0
language-selector==0.1
lxml==4.3.3
MarkupSafe==1.0
matplotlib==3.1.0
netifaces==0.10.4
numpy==1.16.4
oauthlib==2.0.6
oci==2.2.11
oci-cli==2.5.12
PAM==0.4.2
pathtools==0.1.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
pygobject==3.26.1
PyJWT==1.5.3
pyOpenSSL==18.0.0
pyparsing==2.4.0
pyserial==3.4
python-apt==1.6.4
python-dateutil==2.7.3
python-debian==0.1.32
pytz==2016.10
PyYAML==3.13
requests==2.18.4
requests-unixsocket==0.1.5
retrying==1.3.3
service-identity==16.0.0
shape==1.0.0
shapes==0.1.3
six==1.11.0
soupsieve==1.9.1
ssh-import-id==5.7
systemd-python==234
terminaltables==3.1.0
Twisted==17.9.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
virtualenv==16.6.0
watchdog==0.9.0
zope.interface==4.3.2```

**Comment by AnykeyNL** [comment]
You probably only downloaded the list_instances.py file and not the entire repository.
